repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: fix-byte-order-marker   # Prevents weird UTF-8 encoding edge cases
  - id: check-case-conflict     # Check if case-insensitive filesystems would bork
  - id: check-docstring-first   # Check for if docstring was misplaced
  - id: check-executables-have-shebangs
  - id: check-json              # Checks for valid json
  - id: check-merge-conflict    # Checks strings that look like a committed merge conflict
  - id: check-xml               # Checks for valid xml
  - id: check-yaml              # Checks for valid yaml
  - id: end-of-file-fixer       # Checks for ending with a newline
  - id: mixed-line-ending       # Consistent LF or CRLF
  - id: trailing-whitespace     # No trailing whitespace
- repo: https://github.com/fsfe/reuse-tool
  rev: v2.0.0
  hooks:
  - id: reuse
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: ["--toml", "pyproject.toml"]
    additional_dependencies:
    - tomli
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["--configfile", "pyproject.toml"]
    additional_dependencies:
    - bandit[toml]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.282
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    args: ["--config-file", "pyproject.toml"]
    additional_dependencies:
    - tomli
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
- repo: local
  hooks:
  - id: lower-case-only
    name: lower case only
    entry: filenames must be lower-case or lower_case only
    language: fail
    files: '[^a-z0-9._/-]'
    exclude: |
      (?x)^(
          .reuse/|
          LICENSES/|
          public/|
          Makefile|
          CONTRIBUTING.md|
          CREDITS.md|
          LICENSE.md|
          README.md
      )
  - id: check-gdscript
    name: check gdscript
    entry: gdformat
    language: system
    files: \.gd$
    exclude: |
      (?x)^(
          addons/|
          plug.gd
      )
  - id: check-shaders
    name: check shaders
    entry: clang-format
    args:
      - --style=file
      - -Werror
    language: system
    files: \.gdshader$
    exclude: ^addons/
  - id: lint-gdscript
    name: lint gdscript
    entry: gdlint
    language: system
    files: \.gd$
    exclude: |
      (?x)^(
          addons/|
          plug.gd
      )
