name: Release Packaging

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-packaging:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            output: Greeter.exe
            preset: Windows Desktop

          - platform: linux
            output: Greeter.x86_64
            preset: Linux/X11

          - platform: web
            output: index.html
            preset: Web

          - platform: mac
            output: Greeter.zip
            preset: macOS

    name: ${{ matrix.preset }} Export
    steps:
      - uses: actions/checkout@v3

      - name: Setup Versions Vars
        run: |
          echo "game_version=$(cat .version)" >> $GITHUB_ENV
          echo "godot_version=$(cat .godot_version)" >> $GITHUB_ENV
          ./bump_version.sh

      - name: Export Greeter
        uses: ./.github/actions/export-game
        with:
          platform: ${{ matrix.platform }}
          output: ${{ matrix.output }}
          preset: ${{ matrix.preset }}
          version: ${{ env.game_version }}
          godot_version: ${{ env.godot_version }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: Greeter-${{ matrix.platform }}-v${{ env.game_version }}
          path: build/${{ matrix.platform }}

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        if: ${{ matrix.platform == 'web' }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        if: ${{ matrix.platform == 'web' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
